In [1]:
import numpy as np
#Task1
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

Empty array (2x2):
 [[5.45847086e-315 0.00000000e+000]
 [0.00000000e+000 2.60036441e-315]]


In [2]:
#Task2
ones_array = np.ones((4, 2))
print("All ones array (4x2):\n", ones_array)

All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#Task3
filled_array = np.full((3, 4), 5)
print("Array filled with 5s (3x4):\n", filled_array)

Array filled with 5s (3x4):
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [4]:
#Task4
original_array_for_zeros = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_like_array = np.zeros_like(original_array_for_zeros)
print("Zeros like array:\n", zeros_like_array)

Zeros like array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#Task5
original_array_for_ones = np.array([[10, 20], [30, 40]], dtype=int)
ones_like_array = np.ones_like(original_array_for_ones)
print("Ones like array:\n", ones_like_array)

Ones like array:
 [[1 1]
 [1 1]]


In [6]:
#Task6
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("NumPy array from list:\n", numpy_array_from_list)
print("Type of NumPy array:\n", type(numpy_array_from_list))

NumPy array from list:
 [1 2 3 4]
Type of NumPy array:
 <class 'numpy.ndarray'>


In [7]:
#Problem2
#Task1
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#Task2
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Task3
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Task4
random_array_30 = np.random.random(30)
mean_of_array = random_array_30.mean()
print("Random array of size 30:\n", random_array_30)
print("Mean of the array:\n", mean_of_array)

Random array of size 30:
 [0.6992536  0.52449445 0.81458848 0.85801824 0.47450072 0.96386786
 0.25968085 0.54180371 0.43086588 0.41567414 0.90903865 0.69429714
 0.02120521 0.91716286 0.76704403 0.15946858 0.51710816 0.27002353
 0.62213793 0.80504181 0.83565759 0.88112355 0.12149267 0.2307447
 0.55367142 0.65639375 0.61756074 0.05320545 0.00506996 0.08814708]
Mean of the array:
 0.5236114244196364


In [11]:
#Task5
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("10x10 random array:\n", random_array_10x10)
print("Minimum value:\n", min_value)
print("Maximum value:\n", max_value)

10x10 random array:
 [[7.46850767e-01 5.27938129e-01 7.95012481e-01 6.07776160e-01
  8.44823563e-01 6.81057428e-01 3.63574478e-01 1.40898075e-01
  1.77484348e-01 2.30274719e-02]
 [2.67789220e-01 2.51583398e-01 9.49984750e-01 9.10783667e-01
  4.89457920e-01 3.16439445e-01 6.50118759e-01 1.81996947e-01
  5.25186522e-01 5.86125530e-01]
 [4.32695127e-01 9.71244414e-01 7.67266678e-01 7.99316873e-01
  8.06467984e-01 6.56576027e-02 2.57852073e-01 7.91068664e-01
  2.60164289e-01 8.97361284e-02]
 [1.20790978e-01 5.50007341e-01 1.37494656e-01 3.51779804e-01
  1.46738646e-01 6.62269283e-02 2.14885959e-01 6.32819813e-01
  2.99047745e-01 5.79190759e-01]
 [8.26241355e-01 2.81699852e-02 8.44830276e-02 3.37630446e-01
  6.47286119e-01 6.84084079e-01 8.05252094e-01 3.31491518e-01
  2.63375198e-02 5.71224387e-01]
 [1.29284459e-02 8.20385654e-01 8.97654614e-01 3.01618849e-01
  3.46699087e-01 8.81765035e-01 7.71198391e-01 2.49287038e-03
  6.79553149e-01 2.22534330e-01]
 [4.87160579e-01 5.94020415e-01 9.209

In [12]:
#Task6
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element replaced by 1:\n", zero_array)

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#Task7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

Reversed array:
 [0 4 0 0 2 1]


In [14]:
#Task8
rows, cols = 5, 5
border_array = np.ones((rows, cols))
border_array[1:-1, 1:-1] = 0
print("Array with 1s on border and 0s inside:\n", border_array)

Array with 1s on border and 0s inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#Task9
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)

8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [16]:
#Problem3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Array x:\n", x)
print("Array y:\n", y)
print("Array v:\n", v)
print("Array w:\n", w)

Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Array v:
 [ 9 10]
Array w:
 [11 12]


In [17]:
#Task1
array_sum = x + y
print("Sum of x and y:\n", array_sum)

Sum of x and y:
 [[ 6  8]
 [10 13]]


In [18]:
#Task2
array_difference = x - y
print("Difference of x and y:\n", array_difference)

Difference of x and y:
 [[-4 -4]
 [-4 -3]]


In [19]:
#Task3
integer_factor = 3
array_product = x * integer_factor
print(f"Product of x with {integer_factor}:\n", array_product)

Product of x with 3:
 [[ 3  6]
 [ 9 15]]


In [20]:
#Task4
array_squared = x**2
print("Square of each element in x:\n", array_squared)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [21]:
#Task5
dot_vw = np.dot(v, w)
print("Dot product of v and w:\n", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [22]:
#Task6
concat_xy_rows = np.vstack((x, y))
print("Concatenating x and y along rows:\n", concat_xy_rows)


concat_vw_cols = np.hstack((v[:, np.newaxis], w[:, np.newaxis]))
print("Concatenating v and w along columns:\n", concat_vw_cols)

Concatenating x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenating v and w along columns:
 [[ 9 11]
 [10 12]]


In [23]:
#Task7
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print(f"Caught an error during concatenation: {e}")

Caught an error during concatenation: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Error Explaination:
The error occurs because NumPy requires arrays to have the same number of dimensions when using concatenate, vstack, or hstack.
Here, x is 2D (shape (2,2)) while v is 1D (shape (2,)), so they cannot be combined directly.

In [24]:
#Problem4
#Task1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("Array A:\n", A)
print("Array B:\n", B)

Array A:
 [[3 4]
 [7 8]]
Array B:
 [[5 3]
 [2 1]]


In [25]:
#Question1
A_inv = np.linalg.inv(A)
product_AA_inv = np.dot(A, A_inv)

print("Inverse of A (A⁻¹):\n", A_inv)
print("Product A * A⁻¹:\n", product_AA_inv)
print("Is A * A⁻¹ approximately equal to Identity matrix?\n", np.allclose(product_AA_inv, np.eye(A.shape[0])))

Inverse of A (A⁻¹):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A⁻¹ approximately equal to Identity matrix?
 True


In [26]:
#Question2
AB = np.dot(A, B)
BA = np.dot(B, A)

print("Product AB:\n", AB)
print("Product BA:\n", BA)
print("Is AB equal to BA?\n", np.array_equal(AB, BA))

Product AB:
 [[23 13]
 [51 29]]
Product BA:
 [[36 44]
 [13 16]]
Is AB equal to BA?
 False


In [27]:
#Question3
AB_transpose = (np.dot(A, B)).T
B_transpose_A_transpose = np.dot(B.T, A.T)

print("(AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", B_transpose_A_transpose)
print("Is (AB)ᵀ approximately equal to BᵀAᵀ?\n", np.allclose(AB_transpose, B_transpose_A_transpose))

(AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Is (AB)ᵀ approximately equal to BᵀAᵀ?
 True


# Task2
The system of linear equations is:

2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

This can be represented in matrix form as AX = B, where:

A = [[2, -3, 1],
     [1, -1, 2],
     [3,  1, -1]]

X = [[x],
     [y],
     [z]]

B = [[-1],
     [-3],
     [9]]

In [28]:

A_coeffs = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3,  1, -1]])


B_constants = np.array([[-1],
                        [-3],
                        [9]])

print("Coefficient Matrix A:\n", A_coeffs)
print("Constants Vector B:\n", B_constants)

Coefficient Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Vector B:
 [[-1]
 [-3]
 [ 9]]


In [29]:
#Task3

A_coeffs_inv = np.linalg.inv(A_coeffs)

print("Inverse of A (A⁻¹):\n", A_coeffs_inv)


X_solution = np.dot(A_coeffs_inv, B_constants)

print("Solution for X (x, y, z):\n", X_solution)

x_val = X_solution[0][0]
y_val = X_solution[1][0]
z_val = X_solution[2][0]

print(f"The solution is: x = {x_val:.2f}, y = {y_val:.2f}, z = {z_val:.2f}")

Inverse of A (A⁻¹):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution for X (x, y, z):
 [[ 2.]
 [ 1.]
 [-2.]]
The solution is: x = 2.00, y = 1.00, z = -2.00
